
# Auto generated by Django helper
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass # fill custom model fields here..

    def __str__(self):
        return self.username
