
# Auto generated by Django helper
from rest_framework import generics, permissions, viewsets
from django.contrib.auth import get_user_model

from .serializers import *

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = CustomUserSerializer

class CurrentUserView(generics.RetrieveAPIView):
    serializer_class = CustomUserSerializer
    def get_object(self):
        return self.request.user

